FROM node:20-alpine

WORKDIR /usr/src/app

# Instalar ferramentas necessárias
RUN apk add --no-cache wget bash curl

# Instalar PNPM globalmente
RUN npm install -g pnpm@latest

# Copiar arquivos de configuração primeiro
COPY package*.json tsconfig*.json typeorm.config.ts ./

# Instalar dependências com PNPM
RUN pnpm install

# Expor a porta da aplicação
EXPOSE ${PORT:-3005}

# Comando para inicialização em modo de desenvolvimento
CMD ["pnpm", "run", "start:dev"]