### Rota principal - Hello World
GET http://localhost:3001/

### Rota para simular erros e coletar métricas de erros
GET http://localhost:3001/error-demo

### Rota para registrar eventos personalizados
GET http://localhost:3001/event-demo

### Rota de métricas do Prometheus - retorna todas as métricas coletadas
GET http://localhost:3001/metrics

### Criar um usuário - este endpoint interagirá com o PostgreSQL
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com"
}

### Listar todos os usuários - este endpoint interagirá com o PostgreSQL
GET http://localhost:3001/users

### Buscar um usuário específico - este endpoint interagirá com o PostgreSQL
GET http://localhost:3001/users/1

### Rota com latência simulada
GET http://localhost:3001/users/simulate-latency

### Documentação Swagger UI
GET http://localhost:3001/api-docs

### Testar as outras chamadas em sequência para visualizar no Grafana
# Você pode enviar essas requisições repetidamente para gerar dados significativos no dashboard